spring:
  application:
    name: ribbo

server:
  port: 3001

#配置注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka1:2002/eureka

#配置重试的次数和更换服务器的次数
ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: true
